server {
    listen 80;
    server_name latin-vocab.trainer latein-vokabel-trainer.arg-server.de;

    location = /favicon.ico {
        alias /var/www/latin-vocab-trainer/flask_app/static/favicon.ico;
        access_log off;
        log_not_found off;
        expires 30d;
    }

    location /static/ {
        alias /var/www/latin-vocab-trainer/flask_app/static/;
        try_files $uri =404;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}